Update emergency.yaml

diff --git a/.github/workflows/emergency.yaml b/.github/workflows/emergency.yaml
--- a/.github/workflows/emergency.yaml
+++ b/.github/workflows/emergency.yaml
@@ -113,11 +113,11 @@ jobs:
         with:
           github-token: ${{ steps.app-token.outputs.token }}
           
-      - name: Merge PR
-        if: env.AUTHOR_IS_MEMBER == 'true'
-        run: |
-          echo "🚀 Attempting to auto-merge PR #$PR_NUMBER..."
-          gh pr merge --admin --squash "$PR_URL" || echo "⚠️ Auto-merge failed. Check branch protections."
-        env:
-          PR_URL: ${{ github.event.pull_request.html_url }}
-          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+#      - name: Merge PR
+#        if: env.AUTHOR_IS_MEMBER == 'true'
+#        run: |
+#          echo "🚀 Attempting to auto-merge PR #$PR_NUMBER..."
+#          gh pr merge --admin --squash "$PR_URL" || echo "⚠️ Auto-merge failed. Check branch protections."
+#        env:
+#          PR_URL: ${{ github.event.pull_request.html_url }}
+#          GH_TOKEN: ${{ steps.app-token.outputs.token }}
